# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/candidatos/')),
                ('legenda', models.CharField(blank=True, max_length=100)),
                ('nascimento', models.DateField()),
                ('formacao', models.CharField(blank=True, max_length=100)),
                ('renda_declarada', models.FloatField()),
                ('posicionamento', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
