# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='posicionamento',
        ),
        migrations.AddField(
            model_name='candidato',
            name='posicionamento',
            field=models.ManyToManyField(blank=True, to='core.Posicionamento'),
        ),
    ]
