# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160305_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidato',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
